# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0002_case_run_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_run_info',
            name='task_name',
            field=models.TextField(default='noName', max_length=200),
        ),
        migrations.AlterField(
            model_name='case_run_info',
            name='case_name',
            field=models.TextField(max_length=5000),
        ),
    ]
