# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0003_auto_20180214_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_run_info',
            name='duration',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='case_run_info',
            name='num',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
