# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbiter', '0004_auto_20180223_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_run_info',
            name='deleted',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
